logging:
  level:
    '[com.anabatic.catalog]': TRACE
    
#spring datasource
spring:
  datasource:
    connection-timeout: 60000
    idle-timeout: 60000
    max-lifetime: 180000
    maximum-pool-size: 10
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_catalog
    username: root
    password: 
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      jdbc:
        batch_size: 100
    show-sql: true

app:
  currency: IDR
  timezone: Asia/Jakarta
  welcome-text: hellow world ade, are u ready tu lose? hAHAHAH. dari property ini
cloud:
  api-key: ${CLOUD_KEY2}
server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile:
      - development

server:
  port: 8010

app:
  welcome-text: hellow world ade, THIS IS DEVELOPMENT
  
---
spring:
  config:
    activate:
      on-profile:
      - test
server:
  port: 8015

app:
  welcome-text: hellow world ade, THIS IS TEST
  
---
spring:
  config:
    activate:
      on-profile:
      - production

server:
  port: 8020

app:
  welcome-text: hellow world ade, THIS IS PRODUCTION